import { Examples } from '@/components/examples';
import { SearchBox } from '@/components/search-box';

const PRINCIPLES = [
  {
    title: 'Indexed, not scraped',
    body: 'A custom indexer reads blocks, receipts and logs over JSON-RPC, waits for confirmations and rolls back on reorgs.',
  },
  {
    title: 'Every figure is traceable',
    body: 'Counts link back to transactions and logs. Each page states the block range it covers.',
  },
  {
    title: 'Facts, inferences, heuristics',
    body: 'Observed data, deterministic inferences and rule-based classifications are labelled differently. Nothing is generated by AI.',
  },
];

export default function HomePage() {
  return (
    <div className="space-y-12">
      <section className="mx-auto max-w-3xl pt-10 text-center">
        <h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">
          Ethereum On-Chain Intelligence
        </h1>
        <p className="mt-3 text-ink-2">Explore Ethereum activity using verifiable on-chain data.</p>
        <div className="mt-8 text-left">
          <SearchBox autoFocus />
        </div>
      </section>

      <Examples />

      <section className="grid gap-4 sm:grid-cols-3">
        {PRINCIPLES.map((p) => (
          <div key={p.title} className="rounded-lg border border-line bg-surface p-4">
            <h2 className="text-sm font-semibold">{p.title}</h2>
            <p className="mt-1 text-sm text-ink-2">{p.body}</p>
          </div>
        ))}
      </section>
    </div>
  );
}
